name:                generic-crud-servant-persistent
version:             0.1.0.0
github:              "sfeitosa/generic-crud-servant-persistent"
license:             BSD3
author:              "Samuel Feitosa"
maintainer:          "feitosa.sams [at] gmail [dot] com"
copyright:           "LGPL v3"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sfeitosa/generic-crud-servant-persistent#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- monad-logger
- mtl
- persistent
- persistent-sqlite
- persistent-template
- servant-server
- text
- time
- transformers
- wai
- warp

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  main-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - generic-crud-servant-persistent

tests:
  main-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - generic-crud-servant-persistent
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
